---
creation_rules:
  - path_regex: secret-.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
        - age1r95vyqhek2s0596qngem77wqxl7cc3y9v4c5rjwsenvesmx9v30s8cz5t8
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
        - age1r95vyqhek2s0596qngem77wqxl7cc3y9v4c5rjwsenvesmx9v30s8cz5t8
