---
creation_rules:
  - path_regex: secret-.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
        - age188ehznumr5f8l5x5a3hvs2kcxd328ud0rxz7ctrtxtje28z3ec8s9ftzgu
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
        - age188ehznumr5f8l5x5a3hvs2kcxd328ud0rxz7ctrtxtje28z3ec8s9ftzgu
