---
creation_rules:
  - path_regex: secret-.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
        - age16p487dapa0y48kcehhn5pdr7e24vg68cvhacepy3c3usdycu6vasn5mwqz
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
        - age16p487dapa0y48kcehhn5pdr7e24vg68cvhacepy3c3usdycu6vasn5mwqz
