---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos

tasks:
  default:
    silent: true
    cmd: task --list
